export const PLAN_LIMITS = {
  Cortesia: {
    companies: 1,
    users: 1,
    equipment: 5,
    requests: 1,
    workOrders: 0,
    maintenances: 0,
    parts: 10,
    features: {
      dashboard_access: true,
      requests_management: true,
      work_orders_management: false,
      maintenances_management: false,
      equipment_management: true,
      parts_management: true,
      company_view_access: true,
      equipment_qrcode_view: false,
      equipment_qrcode_scan: false,
      equipment_edit: true,
      category_management: false,
    },
  },
  Básico: {
    companies: 2,
    users: 3,
    equipment: 25,
    requests: 5,
    workOrders: 0,
    maintenances: 0,
    parts: 50,
    features: {
      dashboard_access: true,
      requests_management: true,
      work_orders_management: false,
      maintenances_management: false,
      equipment_management: true,
      parts_management: true,
      company_view_access: true,
      equipment_qrcode_view: true,
      equipment_qrcode_scan: true,
      equipment_edit: true,
      category_management: true,
    },
  },
  Profissional: {
    companies: 3,
    users: 10,
    equipment: 500,
    requests: 10,
    workOrders: 10,
    maintenances: 10,
    parts: 100,
    features: {
      dashboard_access: true,
      requests_management: true,
      work_orders_management: true,
      maintenances_management: true,
      equipment_management: true,
      parts_management: true,
      company_view_access: true,
      equipment_qrcode_view: true,
      equipment_qrcode_scan: true,
      equipment_edit: true,
      category_management: true,
    },
  },
  Ultimate: {
    companies: 5,
    users: 100,
    equipment: 1000,
    requests: 250,
    workOrders: 250,
    maintenances: 250,
    parts: 2500,
    features: {
      dashboard_access: true,
      requests_management: true,
      work_orders_management: true,
      maintenances_management: true,
      equipment_management: true,
      parts_management: true,
      company_view_access: true,
      equipment_qrcode_view: true,
      equipment_qrcode_scan: true,
      equipment_edit: true,
      category_management: true,
    },
  },
  'Ultimate Vitálicio': {
    companies: Infinity,
    users: Infinity,
    equipment: Infinity,
    requests: Infinity,
    workOrders: Infinity,
    maintenances: Infinity,
    parts: Infinity,
    features: {
      dashboard_access: true,
      requests_management: true,
      work_orders_management: true,
      maintenances_management: true,
      equipment_management: true,
      parts_management: true,
      company_view_access: true,
      equipment_qrcode_view: true,
      equipment_qrcode_scan: true,
      equipment_edit: true,
      category_management: true,
    },
  },
  Admin: {
    companies: Infinity,
    users: Infinity,
    equipment: Infinity,
    requests: Infinity,
    workOrders: Infinity,
    maintenances: Infinity,
    parts: Infinity,
    features: {
      dashboard_access: true,
      requests_management: true,
      work_orders_management: true,
      maintenances_management: true,
      equipment_management: true,
      parts_management: true,
      company_view_access: true,
      equipment_qrcode_view: true,
      equipment_qrcode_scan: true,
      equipment_edit: true,
      user_management_system: true,
      admin_license_management: true,
      admin_settings_access: true,
      category_management: true,
    },
  },
};

export const getPlanLimits = (planName) => {
  if (!planName) return PLAN_LIMITS.Cortesia;
  const lowerCasePlanName = planName.toLowerCase();

  if (lowerCasePlanName.includes('admin')) return PLAN_LIMITS.Admin;
  if (lowerCasePlanName.includes('vitálicio')) return PLAN_LIMITS['Ultimate Vitálicio'];
  if (lowerCasePlanName.includes('ultimate')) return PLAN_LIMITS.Ultimate;
  if (lowerCasePlanName.includes('profissional')) return PLAN_LIMITS.Profissional;
  if (lowerCasePlanName.includes('básico')) return PLAN_LIMITS.Básico;
  return PLAN_LIMITS.Cortesia;
};